# # SELECT
# #     FI.ID,
# #     FNI.FISH_NAME,
# #     FI.LENGTH
# # FROM FISH_INFO AS FI
# # JOIN FISH_NAME_INFO AS FNI
# # ON FI.FISH_TYPE = FNI.FISH_TYPE
# # WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
# #     SELECT
# #         FISH_TYPE,
# #         MAX(LENGTH)
# #     FROM FISH_INFO
# #     WHERE LENGTH IS NOT NULL
# #     GROUP BY FISH_TYPE
# # )
# # ORDER BY FI.ID ASC

# SELECT I.ID, N.FISH_NAME, I.LENGTH FROM FISH_INFO I JOIN FISH_NAME_INFO N  ON I.FISH_TYPE = N.FISH_TYPE
# WHERE I.LENGTH IN 
# (
#     SELECT MAX(LENGTH) 
#     FROM FISH_INFO 
#     WHERE FISH_TYPE = I.FISH_TYPE
# )
# ORDER BY ID

SELECT
    FI.ID,
    FNI.FISH_NAME,
    FI.LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH)
    IN
        (SELECT
            FISH_TYPE,
            MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE)
ORDER BY FI.ID ASC